# Generated by Django 2.2.1 on 2019-05-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scour',
            new_name='score',
        ),
    ]
