# Generated by Django 2.2.1 on 2019-05-28 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('anonymous'), to=settings.AUTH_USER_MODEL),
        ),
    ]
