# Generated by Django 2.2.1 on 2019-05-29 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0002_auto_20190528_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
